Collision system changes
Brick-Studios/BeastArena pull request #12
Opened 2019-10-15 16:13 UTC by LuukSantegoeds

Combine with this pull request

2019-10-15 17:07 UTC, JanSchollaert requested changes

2019-10-15 17:07 UTC, JanSchollaert commented on src/entities/entity_factory.cpp
> +    // comps->push_back(std::make_unique<PlayerComponent>());
Remove this

2019-10-15 17:07 UTC, JanSchollaert commented on src/systems/movement_system.cpp
> +            // also check whether you are standing on a platform
Unnecessary comment imo

2019-10-16 08:45 UTC, JanSchollaert approved these changes

2019-10-16 09:19 UTC, Bram-Boris approved these changes

2019-10-16 09:24 UTC, merged