Added level loading and scene manager
Brick-Studios/BeastArena pull request #27
Opened 2019-11-05 15:31 UTC by Bram-Boris

# Description

Please include a summary of the change and which user story is implemented. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Screenshot(s)

# How can this be tested?

Please describe the tests that you can run to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Included 1 or more screenshots
- [ ] Code is const correct

2019-11-05 18:04 UTC, JanSchollaert submitted a review, later dismissed
Some small naming change requests

2019-11-05 18:04 UTC, JanSchollaert commented on include/exceptions/notEnoughPlayerSpawnsException.hpp
> +class NotEnoughPlayerSpawnsException : public std::exception {
notEnoughPlayerSpawnsException.hpp 
wrong naming (snake_case)

2019-11-05 18:04 UTC, JanSchollaert commented on include/exceptions/sizeMismatchException.hpp
> +class SizeMismatchException : public std::exception {
sizeMismatchException.hpp
wrong naming (snake_case)

2019-11-05 18:04 UTC, JanSchollaert commented on include/exceptions/sizeMismatchException.hpp
> +  virtual const char* what() const throw() {
Maybe a comment about what what() does? Its kind of a strange name

2019-11-05 18:04 UTC, JanSchollaert commented on lib/controllers/game_controller.cpp
> +    scene_manager->loadLevel(level.get());
Is this just for testing? If not it shouldnt be in createTestEntities()

2019-11-05 20:33 UTC, Peter-JanGootzen commented on include/exceptions/sizeMismatchException.hpp
> +  virtual const char* what() const throw() {
TOP KEK :rofl:

2019-11-08 16:42 UTC, Peter-JanGootzen requested changes

2019-11-08 16:42 UTC, Peter-JanGootzen commented on include/controllers/game_controller.hpp
> +    std::shared_ptr<SceneManager> scene_manager;
This can be a unique_ptr

2019-11-08 16:42 UTC, Peter-JanGootzen commented on lib/scenes/scene_manager.cpp
> +void SceneManager::loadLevel(Level* level) {
level should be a reference

2019-11-08 16:42 UTC, Peter-JanGootzen commented on lib/controllers/game_controller.cpp
> +    auto level = std::unique_ptr<Level>(new Level(level_json, SCREEN_WIDTH, SCREEN_HEIGHT));
No need to allocate this on heap, just make it a local variable and then pass it to the loadLevel function.

2019-11-08 21:10 UTC, Peter-JanGootzen approved these changes
I was thinking of suggesting to use the visitor pattern in the scene_manager, because you now have a nice inheritance tree with scene, level (and soon menu) but you have to call the correct function instead of a generic one. But even though this would _cool and correct_, I can't think of any scenario in a game where you wouldn't know whether you currently want to load a level or a menu. If you don't know a scenario either, then I'll approve this PR.

2019-11-08 21:40 UTC, Bram-Boris commented
I also can not think of any scenario :wink:

2019-11-11 10:58 UTC, JanSchollaert approved these changes
Only thing is that the platforms are very dark and the gorilla as well which makes it harder to see everything clearly. But this is easily fixed by using different textures.

2019-11-11 12:18 UTC, merged