Critters
Brick-Studios/BeastArena pull request #36
Opened 2019-11-20 23:47 UTC by JanSchollaert

# Description

ARTIFICIAL INTELLIGENCE BUNNIES

Bunnies (critters) will randomly move around for a random amount of time with a random speed, if the bunny reaches a wall and tries to move it will always move in the opposite direction. If a bunny hits a wall it will also start jumping.

## Screenshot(s)

[](https://imgur.com/a/lA3Nhdg)

# How can this be tested?

- Are there critters moving around randomly?
- Can you pick up a critter?
- When you drop a critter does it continue moving?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Included 1 or more screenshots
- [ ] Code is const correct

2019-11-21 15:03 UTC, MarkMeer reviewed
A few comments/questions about the things you did. Looks great overall, well done. Only thing I am not sure about is how Bob rates the as an AI. Overall great changes you've made 👍 .

2019-11-21 15:03 UTC, MarkMeer commented on assets/levels/box.json
> +        }
At the moment, we have a lot of critters, for the final build we should maybe remove a few? I though that we would only have one critter walking around the level. Not sure what anyone's else thought is on this matter.

2019-11-21 15:03 UTC, MarkMeer commented on lib/systems/movement_system.cpp
> -                vx = (TERMINAL_VELOCITY * -1) / mass;
I think these brackets can ben retained as they give a better understanding of what is happening as it is no TERMINAL_VELOCITY * -1 * Mass but it gets divided by mass. Not a PR killer, but I would've left it as it was for a better understanding.

2019-11-21 15:03 UTC, MarkMeer commented on include/components/wandering_component.hpp
> +    DeathFunction on_death;
I would rather see a health component which' health gets set to 0 for the critter and the on death method that is stored in it. Otherwise, every wandering entity should be able to die.

2019-11-21 15:03 UTC, MarkMeer commented on lib/systems/critter_system.cpp
> +                // Right
Give these comments a bit more content. There is no information of what you are checking left and right as it is not mentioned earlier in the code either. It is a lot of code, which is no problem, but a few more comments would improve read-ability.

2019-11-21 15:42 UTC, JanSchollaert commented on lib/systems/movement_system.cpp
> -                vx = (TERMINAL_VELOCITY * -1) / mass;
Well they were left out on the other if statement as well so I just made them the same

2019-11-21 16:24 UTC, Peter-JanGootzen requested changes

2019-11-21 16:24 UTC, Peter-JanGootzen commented on assets/levels/box.json
> +        }
I agree, have one or two critters in the game. No more.

2019-11-21 16:24 UTC, Peter-JanGootzen commented on include/components/wandering_component.hpp
> +    int random = 0;
The random variable should have its purpose made more clear by making it a Direction. In the system you generate a number between 0 and 1 and then use it as a direction. If you generate the random, turn it into a Direction and then store and use it, the code would be way nicer to read.

2019-11-21 16:24 UTC, Peter-JanGootzen commented on lib/systems/movement_system.cpp
> -                vx = (TERMINAL_VELOCITY * -1) / mass;
I agree with @markJavab, use brackets whenever it can make your intent more clear, even though it does not provide any mathematical function.

2019-11-21 16:25 UTC, JanSchollaert commented on lib/systems/movement_system.cpp
> -                vx = (TERMINAL_VELOCITY * -1) / mass;
![image](https://user-images.githubusercontent.com/33418574/69356532-e6c2da00-0c83-11ea-938d-f1af4d00eb78.png)

Then should have said that at the movement pull request

2019-11-21 16:32 UTC, Peter-JanGootzen commented on lib/systems/movement_system.cpp
> -                vx = (TERMINAL_VELOCITY * -1) / mass;
True, but we gotta start doing things right somewhere.

2019-11-21 18:02 UTC, Peter-JanGootzen approved these changes
:1st_place_medal: great work

2019-11-22 10:59 UTC, MarkMeer approved these changes
👍

2019-11-22 13:27 UTC, merged