Adaptable gameplay speed
Brick-Studios/BeastArena pull request #40
Opened 2019-11-23 10:28 UTC by LuukSantegoeds

# Description
Change the delta time modifier with page up and page down.

**Please note!**
Changing the modifier has no effect on horizontal movement because of terminal velocity!

## Screenshot(s)
No

# How can this be tested?
Combine with [this PR](url). Start the game and change the modifier with page up and page down.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Included 1 or more screenshots
- [X] Code is const correct

2019-11-23 13:01 UTC, Bram-Boris requested changes
I think this feature can be in the engine.

2019-11-23 13:01 UTC, Bram-Boris commented on lib/systems/game_speed_system.cpp
> +    double step_size = 0.2;
This can be a const in hpp

2019-11-23 13:01 UTC, Bram-Boris commented on lib/systems/game_speed_system.cpp
> +GameSpeedSystem::GameSpeedSystem(std::shared_ptr<EntityManager> em, double *delta_time_modifier) : System(em), delta_time_modifier(delta_time_modifier) {};
I think passing by reference would be better.

2019-11-23 13:16 UTC, JanSchollaert approved these changes

2019-11-23 13:16 UTC, JanSchollaert commented on lib/systems/game_speed_system.cpp
> +#include "player_input.hpp"
Unnecessary whitelines but not that problematic

2019-11-23 13:18 UTC, JanSchollaert commented
@Bram-Boris I thought it should be in the engine as well but wasn't sure because you are using inputs to set them and wasn't sure if thats game specific

2019-11-23 13:37 UTC, LuukSantegoeds commented
I think that having the modifier system in the game is perfectly fine. Mark agrees with me so the truth has been spoken :P

2019-11-23 13:41 UTC, JanSchollaert submitted a review, later dismissed
nice

2019-11-23 19:25 UTC, Peter-JanGootzen commented
We could maybe fix the vertical velocity by adding a separate speed_modifier parameter to System::update.

2019-11-28 13:51 UTC, JanSchollaert commented on include/player_input.hpp
> +    HOME
Changed these to SPEED_UP SPEED_DOWN AND SPEED_RESET, or something like this

2019-11-28 15:32 UTC, JanSchollaert approved these changes
nice

2019-12-01 16:38 UTC, Bram-Boris approved these changes

2019-12-01 16:46 UTC, merged