Gadget spawners
Brick-Studios/BeastArena pull request #43
Opened 2019-11-24 16:48 UTC by JanSchollaert

# Description

Implemented gadget (weapon) spawners

## Screenshot(s)
![image](https://user-images.githubusercontent.com/33418574/69497946-8a112a80-0ee2-11ea-8d6f-3e816be7a96b.png)

# How can this be tested?

- Can you pick up a weapon?
- If you empty the magazine or drop it off the map does it respawn?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Included 1 or more screenshots
- [ ] Code is const correct

2019-11-27 19:54 UTC, MarkMeer reviewed
One small comment, but nothing major. Great work guys 👍 !

2019-11-27 19:54 UTC, markJavab commented on lib/systems/gadget_spawn_system.cpp
> +    : BeastSystem(ef, em), collision_detector(cd) {}
The collision detector is not used here and can be removed when not necessary in the future. I am not sure whether you both had some slick things for the collision detector in the gadget spawn system so I'll let it up to you ;-).

2019-11-28 16:24 UTC, MarkMeer approved these changes
Thank you Jan 👍

2019-12-02 19:32 UTC, Bram-Boris commented on include/components/hold_component.hpp
> +#ifndef FILE_GADGET_HOLDER_COMPONENT_HPP
No gadget?

2019-12-02 19:37 UTC, Bram-Boris requested changes

2019-12-02 19:37 UTC, Bram-Boris commented on include/components/hold_component.hpp
> +#ifndef FILE_GADGET_HOLDER_COMPONENT_HPP
No gadget?

2019-12-02 19:37 UTC, Bram-Boris commented on include/systems/gadget_spawn_system.hpp
> +#ifndef FILE_GADGET_RESPAWN_SYSTEM_HPP
reeeee

2019-12-02 19:37 UTC, Bram-Boris commented on lib/components/spawn_component.cpp
> +std::string SpawnComponent::SpawnComponent::getNameStatic() {
Double class name?

2019-12-02 19:37 UTC, Bram-Boris commented on lib/entities/entity_factory.cpp
> +
?

2019-12-03 10:24 UTC, MarkMeer approved these changes
Agreed with the changes requested by Bram, not sure how I've missed those, but that's why we have two reviewers 😌.

2019-12-03 12:40 UTC, Bram-Boris approved these changes

2019-12-03 12:45 UTC, merged