Collision Detector 2 ©
Brick-Studios/BeastArena pull request #46
Opened 2019-12-02 19:16 UTC by Peter-JanGootzen

# Description

Please include a summary of the change and which user story is implemented. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Screenshot(s)

# How can this be tested?

Please describe the tests that you can run to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Included 1 or more screenshots
- [ ] Code is const correct

2019-12-03 08:52 UTC, LuukSantegoeds submitted a review, later dismissed
As said in the Engine: "Clearly the artwork is way better than the code" and this PR is no exception.

_This is the spot where I would show you a snippet of the build failing but the error was too long :P_

2019-12-03 13:33 UTC, LuukSantegoeds requested changes
Change the in-air recoil and I approve

2019-12-03 15:22 UTC, MarkMeer approved these changes
Looking good, functionally a few 🐛 but we've discussed those. 


edit: Meant to comment on this, not approve.

2019-12-03 15:22 UTC, MarkMeer commented on lib/controllers/game_controller.cpp
> +    is_trigger_exceptions.insert({ "Player", std::set<std::string> { "Platform" } });
What does this do? Maybe add a comment about its function as 'is_trigger_exceptions' looks like it has something to do with an boolean to show whether it a trigger exception. However, it has a string and a set with strings.

2019-12-03 15:27 UTC, JanSchollaert commented on lib/controllers/game_controller.cpp
> +    is_trigger_exceptions.insert({ "Player", std::set<std::string> { "Platform" } });
Those are for triggers, all triggers have no collision and will fall through everything, critter and weapons should not fall through platforms, so we made trigger exceptions using tags. The entities with the left will now collide with entities with the right tag.

2019-12-04 11:01 UTC, JanSchollaert commented on lib/controllers/game_controller.cpp
> +    is_trigger_exceptions.insert({ "Player", std::set<std::string> { "Platform" } });
I put a comment in the header where it's made

2019-12-06 12:23 UTC, LuukSantegoeds approved these changes
Works gr8

2019-12-06 15:50 UTC, MarkMeer approved these changes
Plays nice 👍

2019-12-06 16:28 UTC, merged